name: Source Coverage
on:
  workflow_dispatch:
  push:
    branches:
      - development
      - ci-*

jobs:
  coverage:
    name: test
    runs-on: [self-hosted, Linux, cloud, high-mem]
    steps:
      - name: ubuntu dependencies
        run: |
          sudo apt-get update && \
          sudo apt-get -y install \
            openssl \
            libssl-dev \
            pkg-config \
            libsqlite3-dev \
            clang-10 \
            git \
            cmake \
            libc++-dev \
            libc++abi-dev \
            libprotobuf-dev \
            protobuf-compiler \
            libncurses5-dev \
            libncursesw5-dev \
            zip \
            build-essential \
            libgtk-3-dev \
            libwebkit2gtk-4.0-dev \
            libsoup2.4-dev \
            curl \
            wget \
            libappindicator3-dev \
            patchelf \
            librsvg2-dev
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
          components: llvm-tools-preview
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features --no-fail-fast
        env:
          RUSTFLAGS: "-C instrument-coverage"
          RUSTDOCFLAGS: "-C instrument-coverage"
          LLVM_PROFILE_FILE: "coverage_data-%p-%m.profraw"
      - id: coverage
        name: Prepare coverage data
        run: |
          cargo install grcov
          grcov . -s . --binary-path ./target/debug -t lcov --branch --ignore-not-existing -o ./target/report.lcov
      - name: Coveralls upload
        uses: toshke/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./target/report.lcov